name: Terraform Deploy

on:
  push:
    paths:
      - "Terraform/**"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: Terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: Terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: Terraform
